# This matrix builds VSYS with various JDKs and will be expanded to cover many more cases.   

name: Build VSYS
on: [push,pull_request]

jobs:
  build:
   runs-on: ubuntu-latest
 
   steps:
   - name: install scala
     run: |
       echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
       sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
       sudo apt-get update
       sudo apt-get install -y sbt
       
   - uses: actions/checkout@v2

   - name: Build and Package
     run: sbt packageAll
        
           
        
